# This is a basic workflow to help you get started with Actions

name: Sonar

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [ master, sonar, dev ]
    pull_request:
        types: [ opened, synchronize, reopened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    analyze:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        name: sonar analysis

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v3
                # Disabling shallow clone is recommended for improving relevancy of reporting
                with:
                    fetch-depth: 0

            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_SONAR }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                with:
                    # Additional arguments to the sonarcloud scanner
                    # Set the sonar.projectBaseDir analysis property
                    #projectBaseDir: .
                    # optional
                    args: >
                        -Dfile.encoding=fr_FR.UTF-8
                        -Dsun.jnu.encoding=fr_FR.UTF-8
                        -Dsonar.sourceEncoding=UTF-8
                        -Dsonar.organization=edgd1er
                        -Dsonar.projectKey=edgd1er_Abeille
                        -Dsonar.verbose=true
                        -Dsonar.exclusions='images/,.git/**,.idea/**,.github/**,.scannerwork/**'
